spring:
 profiles:
  active: dev
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.ysd.entity # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/Mapper/**/*.xml # mapper映射文件
spring:
  profiles: dev
  application:
    name: microservice-product-config #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud_db01?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8 # 数据
    username: root
    password: 521521
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 150 # 等待连接获取的最大超时时间
eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://eureka6001.com:6001/eureka
      instance:
        instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主
        preferIpAddress: true
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.ysd.entity # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/Mapper/**/*.xml # mapper映射文件
spring:
  profiles: prod
  application:
    name: microservice-product-config #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud_db01?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8 # 数据
    username: root
    password: 521521
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 150 # 等待连接获取的最大超时时间
eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://eureka6001.com:6001/eureka
      instance:
        instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主
        preferIpAddress: true